"""empty message

Revision ID: 1d754fe66612
Revises: 87515419769d
Create Date: 2023-05-04 14:25:34.183322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d754fe66612'
down_revision = '87515419769d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poet', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poet')
    # ### end Alembic commands ###
